@echo off
echo Starting Backend Server...
start "Backend Server" cmd /k "cd backend && npm start"
timeout /t 3 /nobreak > nul
echo Starting Frontend Server...
start "Frontend Server" cmd /k "cd frontend && npm run dev"
echo Both servers are starting...
echo.
echo Backend will be available at: http://localhost:5000
echo Frontend will be available at: http://localhost:3000
echo.
echo Press any key to exit...
pause > nul
